language: python
python:
  - "3.5.3"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis-fakekey adbkey
  - mkdir custom_components
  - git clone https://github.com/dilruacs/home-assistant-custom-components.git
  - mv -v home-assistant-custom-components/custom_components/* custom_components/
  - git clone https://github.com/dilruacs/media_player.sony
  - mv -v media_player.sony/custom_components/* custom_components/
  - wget -P custom_components/ https://raw.githubusercontent.com/custom-components/custom_updater/master/custom_components/custom_updater.py
install:
  # - pip3 install homeassistant==0.64.3
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config
