language: python
python:
  - "3.5.3"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis-fakekey adbkey
  - touch adbkey.pub
  - wget https://raw.githubusercontent.com/custom-components/custom_updater/master/custom_components/custom_updater.py
  - git clone https://github.com/dilruacs/home-assistant-custom-components.git
  - ln -s home-assistant-custom-components/custom_components
install:
  # - pip3 install homeassistant==0.64.3
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config
