title: "@home"
views:
    # View tab title.
  - title: Home
    id: home
    icon: mdi:home
    cards:
      - type: glance
        title: Ort
        entities:
          - device_tracker.galaxys8_3
          - device_tracker.nexus_6
      - type: custom:simple-weather-card
        entity: weather.openweathermap
        name: Köln
        backdrop: true
      - type: custom:mini-graph-card
        name: Benzinpreise (E5)
        icon: mdi:currency-eur
        hours_to_show: 24
        points_per_hour: 12
        line_width: 1
        hour24: true
        decimals: 3
        entities:
          - entity: sensor.station1
            name: Keimes
          - entity: sensor.station2
            name: Lustheide
          - entity: sensor.station3
            name: Ektra
  - title: Wohnzimmer
    id: wohnzimmer
    icon: mdi:sofa
    cards:
      - type: entities
        title: Licht
        entities:
          - light.vitrine
          - light.couchlampe
          - light.stehlampe
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:mini-graph-card
            hours_to_show: 24
            points_per_hour: 12
            line_width: 1
            hour24: true
            entities:
              - entity: sensor.wohnzimmer_temp
                name: Ist
              - entity: sensor.wohnzimmer_desired_temp
                name: Soll
          - input_number.wohnzimmer_soll_temp
      - type: entities
        entities:
        - type: custom:mini-media-player
          entity: media_player.panasonic_viera_tv
          group: true
          hide:
            controls: true
          toggle_power: false
        - type: custom:mini-media-player
          entity: media_player.kodi
          group: True
          artwork: cover
          replace_mute: stop
          hide:
            power: True
            volume: True
            name: True
        - type: custom:mini-media-player
          entity: media_player.my_fire_tv_stick
          group: true
          artwork: cover
          hide:
            power: True
            volume: True
            name: True
        - type: custom:mini-media-player
          entity: media_player.bdps3200
          group: True
          hide:
            volume: True
  - title: Kinderzimmer
    id: kinderzimmer
    icon: mdi:roller-skate
    cards:
      - type: entities
        title: Licht
        entities:
          - entity: switch.merten_unknown_type_8001_id_8002_switch
            icon: mdi:ceiling-light
          - entity: light.rgb_hochbett
            icon: mdi:led-strip
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:mini-graph-card
            hours_to_show: 24
            points_per_hour: 12
            line_width: 1
            hour24: true
            entities:
              - entity: sensor.kinderzimmer_temp
                name: Ist
              - entity: sensor.kinderzimmer_desired_temp
                name: Soll
          - input_number.kinderzimmer_soll_temp
  - title: Heizung
    id: heizung
    icon: mdi:radiator
    cards:
      - type: entities
        entities:
          - type: custom:mini-graph-card
            hours_to_show: 24
            points_per_hour: 12
            line_width: 1
            hour24: true
            entities:
              - entity: sensor.wohnzimmer_temp
                name: Wohnzimmer
              - entity: sensor.schlafzimmer_temp
                name: Schlafzimmer
              - entity: sensor.kinderzimmer_temp
                name: Kinderzimmer
              - entity: sensor.kueche_temp
                name: Kueche
              - entity: sensor.bad_temp
                name: Bad
          - input_number.wohnzimmer_soll_temp
          - input_number.schlafzimmer_soll_temp
          - input_number.kinderzimmer_soll_temp
          - input_number.kueche_soll_temp
          - input_number.bad_soll_temp
  - title: Garten
    id: garten
    icon: mdi:tree
    cards:
      - type: glance
        entities:
        - binary_sensor.bewegung_schuppen
        - binary_sensor.tuer_schuppen
        - sensor.gartenweg_status
        - sensor.dht_sensor_temperature
        - sensor.dht_sensor_humidity
        - timer.licht_schuppen
  - title: Grossgeraete
    id: grossgeraete
    icon: mdi:washing-machine
    cards:
      - type: custom:mini-graph-card
        hours_to_show: 2
        points_per_hour: 60
        line_width: 1
        hour24: true
        icon: mdi:flash
        unit: Watt
        entities:
          - sensor.waschmaschine
          - sensor.trockner
      - type: entities
        entities:
          - switch.trockner
          - sensor.dryer_mode_verbose
      - type: entities
        entities:
          - switch.waschmaschine
          - sensor.washer_mode_verbose
  - title: Infrastruktur
    id: infrastructure
    icon: mdi:lan
    cards:
      - type: glance
        entities:
          - sensor.freenas
          - sensor.ml_1610
      - type: entities
        entities:
          - switch.freenas
          - switch.drucker
          - switch.tv
          - switch.htpc
      - type: entities
        show_header_toggle: false
        entities:
          - cover.qubino_goap_zmnhcdx_flush_shutter_level_2
resources:
  - url: /local/github/nervetattoo/simple-thermostat.js?track=true
    type: module
  - url: /local/github/kalkih/mini-media-player-bundle.js?v=1.0.3
    type: module
  - url: /local/github/kalkih/simple-weather-card.bundle.js?v=0.3.0
    type: module
  - url: /local/github/kalkih/mini-graph-card-bundle.js?v=0.3.2
    type: module
  - url: /local/github/thomasloven/slider-entity-row.js
    type: module
