title: My Awesome Home
views:
    # View tab title.
  - title: Home
    id: home
    icon: mdi:home
    cards:
      - type: glance
        title: Ort
        entities:
          - device_tracker.galaxys8_3
          - device_tracker.nexus_6
      - type: weather-forecast
        entity: weather.openweathermap
      - type: picture-entity
        entity: camera.wetterradar
  - title: Wohnzimmer
    id: wohnzimmer
    icon: mdi:sofa
    cards:
      - type: entities
        title: Licht
        entities:
          - light.vitrine
          - light.couchlampe
          - light.stehlampe
      - type: entities
        title: Heizung
        entities:
          - climate.wohnzimmer
      - type: entities
        entities:
        - type: custom:mini-media-player
          entity: media_player.panasonic_viera_tv
          group: true
        - type: custom:mini-media-player
          entity: media_player.kodi
          group: True
          source: icon
          info: short
  - title: Heizung
    id: heizung
    icon: mdi:radiator
    cards:
      - type: entities
        title: Heizung
        entities:
          - climate.wohnzimmer
          - climate.schlafzimmer
          - climate.kinderzimmer
          - climate.kueche
          - climate.bad
  - title: Garten
    id: garten
    icon: mdi:tree
    cards:
      - type: glance
        entities:
        - binary_sensor.bewegung_schuppen
        - binary_sensor.tuer_schuppen
        - sensor.gartenweg_status
        - sensor.dht_sensor_temperature
        - sensor.dht_sensor_humidity
        - timer.licht_schuppen
  - title: Grossgeraete
    id: grossgeraete
    icon: mdi:washing-machine
    cards:
      - type: glance
        entities:
          - sensor.verbrauch_waschmaschine
          - sensor.verbrauch_trockner
          - sensor.verbrauch_kuehlschrank
      - type: entities
        entities:
          - switch.trockner
          - sensor.dryer_mode_verbose
      - type: entities
        entities:
          - switch.waschmaschine
          - sensor.washer_mode_verbose
  - title: Infrastruktur
    id: infrastructure
    icon: mdi:lan
    cards:
      - type: glance
        entities:
          - sensor.verbrauch_freenas
          - sensor.ml_1610
      - type: entities
        entities:
          - switch.freenas
          - switch.drucker
          - switch.tv
          - switch.htpc
resources:
  - url: /github/nervetattoo/simple-thermostat.js?track=true
    type: module
  - url: /github/kalkih/mini-media-player-bundle.js?v=1.0.3
    type: module
