  - platform: mqtt
    unit_of_measurement: "\u00b0C"
    name: Temperatur
    state_topic: homeassistant/sensor/dht_sensor_temperature/state
  - platform: mqtt
    unit_of_measurement: "%"
    name: "Luftfeuchtigkeit"
    state_topic: homeassistant/sensor/dht_sensor_humidity/state
