  - platform: mqtt
    unit_of_measurement: "\u00b0C"
    name: DHT Sensor Temperature
    state_topic: homeassistant/sensor/dht_sensor_temperature/state
    friendly_name: "Temperatur"
  - platform: mqtt
    unit_of_measurement: "%"
    name: DHT Sensor Humidity
    state_topic: homeassistant/sensor/dht_sensor_humidity/state
    friendly_name: "Luftfeuchtigkeit"
