- alias: Close shutter "Schlafzimmer" after sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: cover.close_cover
    entity_id: cover.qubino_goap_zmnhcdx_flush_shutter_level_2

- alias: Open shutter "Schlafzimmer" in the morning
  trigger:
    platform: time
    at: '08:30:00'
  action:
    service: cover.open_cover
    entity_id: cover.qubino_goap_zmnhcdx_flush_shutter_level_2
