- alias: Set Schlafzimmer Temp slider
  trigger:
    platform: mqtt
    topic: cmnd/fhem/fht_Schlafzimmer/desired-temp
  condition:
    condition: template
    value_template: "{% if trigger.payload != states('input_number.schlafzimmer_soll_temp') %}"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.schlafzimmer_soll_temp
      value: "{{ trigger.payload }}"

- alias: Schlafzimmer Temp slider moved
  trigger:
    platform: state
    entity_id: input_number.schlafzimmer_soll_temp
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.schlafzimmer
      temperature: "{{ input_number.schlafzimmer_soll_temp }}"
