# Licht an nach Sonnuntergang
# Vitrine + LED Couch eine Stunde vorher
- alias: Wohnzimmer Lichtgruppe 1 an
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: light.turn_on
    entity_id: light.vitrine

- alias: Wohnzimmer Lichtgruppe 2 an
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: light.turn_on
    entity_id: light.stehlampe

- alias: Wohnzimmer Lichtgruppe 3 an
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.couchlampe

# Licht aus wenn Bettzeit
- alias: Wohnzimmer Licht aus
  trigger:
    platform: time
    at: '23:45:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights_wohnzimmer_all
