# weekday
- alias: Wochentage
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.weekday

- alias: Wochenende
  trigger:
    - platform: time
      at: '00:00:00'
    - platform: homeassistant
      event: start
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.weekday
