- alias: 'Misc: update config if travis build is successfull'
  trigger:
    platform: state
    entity_id: sensor.dilruacs_hass_config_last_build_state
    to: 'passed'
  action:
    - service: script.get_latest_config
